"""Local hackathon backend. Run one Uvicorn worker; converter is injectable."""
import os
import shutil
import uuid
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Annotated

from fastapi import BackgroundTasks, FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse

from backend.app.document_processing.mathml import compile_math

from .converter import convert_pages
from .models import EditDocument, ExtractedDocument, RevisionRequest
from .pages import prepare_document
from .storage import Conflict, NotFound, Store, now

MAX_UPLOAD_BYTES = 10 * 1024 * 1024


def create_app(data_dir=None, converter=None):
    root = Path(data_dir or os.environ.get('EIGENSCRIBE_DATA_DIR', 'data')).resolve()
    convert = converter or convert_pages
    uses_shared_ai_converter = converter is None

    @asynccontextmanager
    async def lifespan(app):
        app.state.store = Store(root)
        app.state.store.recover_interrupted()
        yield

    app = FastAPI(title='EigenScribe Backend', version='0.1.0', lifespan=lifespan)
    app.add_middleware(
        CORSMiddleware,
        allow_origins=[s.strip() for s in os.environ.get(
            'FRONTEND_ORIGINS', 'http://localhost:5173,http://localhost:3000').split(',') if s.strip()],
        allow_methods=['GET', 'POST', 'PATCH'], allow_headers=['Content-Type'],
    )

    @app.exception_handler(NotFound)
    async def not_found(request, exc):
        return JSONResponse(status_code=404, content={'detail': 'Document not found.'})

    @app.exception_handler(Conflict)
    async def conflict(request, exc):
        return JSONResponse(status_code=409, content={'detail': str(exc)})

    def store():
        return app.state.store

    def directory(doc_id):
        # A successful lookup means the ID was generated by this backend.
        store().get(doc_id)
        return root / 'files' / doc_id

    def process(doc_id):
        stage = 'page preparation'
        try:
            doc = store().get(doc_id)
            source = directory(doc_id) / ('original.' + doc['sourceType'])
            prepared = prepare_document(source, doc['sourceType'])
            images = prepared.imagePaths
            stage = 'conversion'
            if uses_shared_ai_converter:
                result = convert(
                    images,
                    provider=doc.get('aiProvider', 'development'),
                    model=doc.get('aiModel', 'development-fixture'),
                )
            else:
                result = convert(images)
            stage = 'converter output validation'
            draft = ExtractedDocument.model_validate(result)
            if any(b.page > len(images) for b in draft.blocks):
                raise ValueError('Converter referenced a nonexistent page.')

            def done(current):
                current.update(
                    title=draft.title, blocks=[b.model_dump() for b in draft.blocks],
                    pages=[{'number': page.number,
                            'imageUrl': f'/documents/{doc_id}/pages/{page.number}',
                            'widthPx': page.widthPx, 'heightPx': page.heightPx,
                            'renderedDpi': page.renderedDpi,
                            'hasEmbeddedText': page.hasEmbeddedText}
                           for page in prepared.pages],
                    status='needs_review', error=None,
                )
            store().update(doc_id, done)
        except Exception:  # noqa: BLE001 - job boundary converts failures to a safe status
            # Never publish provider exception text: it may contain keys or private inputs.
            message = {'page preparation': 'Could not read this file. Use a valid PNG/JPEG or an unencrypted PDF of 1–3 pages.',
                       'conversion': 'Converter failed. Check the converter setup and retry.',
                       'converter output validation': 'Converter returned invalid document data. Check the shared schema.'}[stage]
            def failed(current):
                current.update(status='failed', error=message)
            store().update(doc_id, failed)

    @app.get('/health')
    def health():
        return {'status': 'ok'}

    @app.post('/documents', status_code=202)
    async def upload(
        background_tasks: BackgroundTasks,
        file: Annotated[UploadFile, File()],
        provider: Annotated[str, Form()] = 'development',
        model: Annotated[str, Form()] = 'development-fixture',
    ):
        doc_id = 'doc-' + uuid.uuid4().hex
        folder = root / 'files' / doc_id
        folder.mkdir(parents=True)
        pending = folder / 'incoming'
        try:
            size = 0
            with pending.open('wb') as output:
                while chunk := await file.read(1024 * 1024):
                    size += len(chunk)
                    if size > MAX_UPLOAD_BYTES:
                        raise HTTPException(413, 'Maximum upload size is 10 MiB.')
                    output.write(chunk)
            with pending.open('rb') as source:
                signature = source.read(8)
            if signature.startswith(b'%PDF-'):
                kind = 'pdf'
            elif signature.startswith(b'\x89PNG\r\n\x1a\n'):
                kind = 'png'
            elif signature.startswith(b'\xff\xd8\xff'):
                kind = 'jpg'
            else:
                raise HTTPException(415, 'Upload a PDF, PNG, or JPEG file.')
            pending.rename(folder / f'original.{kind}')
            doc = {
                'id': doc_id,
                'title': 'Processing document',
                'status': 'processing',
                'revision': 1,
                'pages': [],
                'blocks': [],
                'error': None,
                'sourceType': kind,
                'fileName': file.filename or f'notes.{kind}',
                'aiProvider': provider,
                'aiModel': model,
                'sourceUrl': f'/documents/{doc_id}/source',
                'createdAt': now(),
                'updatedAt': now(),
            }
            store().create(doc)
        except Exception:
            shutil.rmtree(folder, ignore_errors=True)
            raise
        finally:
            await file.close()
        background_tasks.add_task(process, doc_id)
        return {'id': doc_id, 'status': 'processing', 'revision': 1}

    @app.get('/documents')
    def list_documents():
        return [{k: d[k] for k in ('id', 'title', 'status', 'revision', 'updatedAt')} for d in store().list()]

    @app.get('/documents/{doc_id}')
    def get_document(doc_id: str):
        return store().get(doc_id)

    @app.get('/documents/{doc_id}/semantic-note')
    def semantic_note(doc_id: str):
        doc = store().get(doc_id)
        if doc['status'] not in ('needs_review', 'ready'):
            raise Conflict('The document is not ready for review.')

        blocks = []
        for block in doc['blocks']:
            kind = block['type']
            semantic = {
                'id': block['id'],
                'kind': kind,
                'text': block['text'] or block['description'] or block['spokenText'],
                'confidence': block.get('confidence', 0),
                'needsReview': block['needsReview'],
                'interpretations': block.get('interpretations', []),
            }
            if kind == 'equation':
                # Compiling to MathML is both the accessible rendering and an objective
                # check on the transcription: LaTeX that will not parse cannot be trusted
                # or published, whatever confidence the model reported.
                compiled = compile_math(block['latex'])
                semantic['math'] = {
                    'latex': block['latex'],
                    'spoken': block['spokenText'],
                    'label': 'Handwritten equation',
                    'variables': [],
                    'mathml': compiled.mathml,
                    'mathmlError': compiled.error,
                    **({'tree': compiled.tree.model_dump(exclude_none=True)} if compiled.tree else {}),
                }
                if not compiled.ok:
                    semantic['needsReview'] = True
            elif kind == 'diagram':
                semantic['altText'] = block['description']
            blocks.append(semantic)

        slug = ''.join(character if character.isalnum() else '-' for character in doc['title'].lower())
        slug = '-'.join(filter(None, slug.split('-'))) or doc_id
        return {
            'id': doc_id,
            'slug': slug,
            'title': doc['title'],
            'source': {
                'name': doc.get('fileName', f"{doc_id}.{doc['sourceType']}"),
                'kind': 'pdf' if doc['sourceType'] == 'pdf' else 'image',
                'pageCount': len(doc['pages']),
                'aiProvider': doc.get('aiProvider'),
                'aiModel': doc.get('aiModel'),
                'documentId': doc_id,
                'revision': doc['revision'],
            },
            'blocks': blocks,
            'status': 'published' if doc['status'] == 'ready' else 'draft',
            'createdAt': doc['createdAt'],
            'updatedAt': doc['updatedAt'],
            'schemaVersion': 1,
        }

    @app.get('/documents/{doc_id}/source')
    def source(doc_id: str):
        doc = store().get(doc_id)
        kind = doc['sourceType']
        mime = {'pdf': 'application/pdf', 'png': 'image/png', 'jpg': 'image/jpeg'}[kind]
        return FileResponse(directory(doc_id) / f'original.{kind}', media_type=mime,
                            headers={'X-Content-Type-Options': 'nosniff'})

    @app.get('/documents/{doc_id}/pages/{page_number}')
    def page_image(doc_id: str, page_number: int):
        doc = store().get(doc_id)
        if page_number not in {p['number'] for p in doc['pages']}:
            raise HTTPException(404, 'Page not found or conversion is not complete.')
        return FileResponse(directory(doc_id) / 'pages' / f'{page_number}.png', media_type='image/png')

    @app.patch('/documents/{doc_id}')
    def edit(doc_id: str, body: EditDocument):
        def change(doc):
            if doc['status'] not in ('needs_review', 'ready'):
                raise Conflict('Only converted documents can be edited.')
            old = {b['id']: b for b in doc['blocks']}
            if {b.id for b in body.blocks} != set(old):
                raise HTTPException(422, 'Preserve existing block IDs. Reordering is supported; adding/deleting blocks is outside this MVP.')
            if any(b.page > len(doc['pages']) for b in body.blocks):
                raise HTTPException(422, 'Block references a nonexistent page.')
            for block in body.blocks:
                previous = old[block.id]
                changed = any(getattr(block, k) != previous[k] for k in ('text', 'latex', 'description'))
                if changed and block.spokenText == previous['spokenText']:
                    raise HTTPException(422, 'Update spokenText together with changed content to prevent stale narration.')
            doc.update(title=body.title, blocks=[b.model_dump() for b in body.blocks], status='needs_review')
        return store().update(doc_id, change, body.expectedRevision)

    @app.post('/documents/{doc_id}/finalize')
    def finalize(doc_id: str, body: RevisionRequest):
        def change(doc):
            if doc['status'] != 'needs_review':
                raise Conflict('Only documents awaiting review can be finalized.')
            if any(b['needsReview'] for b in doc['blocks']):
                raise HTTPException(422, 'Resolve all flagged blocks before finalizing.')
            doc['status'] = 'ready'
        return store().update(doc_id, change, body.expectedRevision)

    @app.post('/documents/{doc_id}/retry', status_code=202)
    def retry(doc_id: str, body: RevisionRequest, background_tasks: BackgroundTasks):
        def change(doc):
            if doc['status'] != 'failed':
                raise Conflict('Only failed documents can be retried.')
            doc.update(status='processing', error=None)
        doc = store().update(doc_id, change, body.expectedRevision)
        background_tasks.add_task(process, doc_id)
        return {'id': doc_id, 'status': doc['status'], 'revision': doc['revision']}

    return app


app = create_app()
